FROM ubuntu:18.04

RUN su

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y python3.6
RUN apt-get install -y python-dev python-pip python3-dev python3-pip
RUN apt-get install -y libx11-dev libgtk-3-dev libboost-python-dev
RUN apt-get install -y python3-testresources
RUN apt-get install -y build-essential checkinstall cmake pkg-config yasm

RUN pip3 install --upgrade pip

RUN pip3 install --upgrade virtualenv virtualenvwrapper

RUN virtualenv wittyimage

RUN /bin/bash -c "source /wittyimage/bin/activate"

RUN pip3 install numpy scipy matplotlib scikit-image scikit-learn ipython pandas

RUN pip3 install opencv-contrib-python==3.4.3.18

RUN pip3 install dlib

RUN pip3 install django djangorestframework

# Add code
ADD . /src

# Expose
EXPOSE 8002


#set the working directorly
WORKDIR /src